version: '3'
services:
  skmapi:
    build: ./skm-api
    ports:
    - "11111:11111"
    restart: on-failure:5
    depends_on:
      - skmdb
  skmclient:
    build: ./skm-client
    ports:
    - "22222:22222"
  skmdb:
    build: ./db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: skmcontrol
      MYSQL_USER: skmcontroler
      MYSQL_PASSWORD: pwd